- type: entity
  parent: CP14ClothingCloakBase
  id: CP14ClothingCloakGuardBase
  abstract: true
  name: "guard's cloak"
  description: Shoulder cape in the standard Imperial Guard colors

- type: entity
  parent: CP14ClothingCloakGuardBase
  id: CP14ClothingCloakGuardBlue
  components:
  - type: Sprite
    sprite: _CP14/Clothing/Cloak/Roles/Guard/blue.rsi
  - type: Clothing
    sprite: _CP14/Clothing/Cloak/Roles/Guard/blue.rsi

- type: entity
  parent: CP14ClothingCloakGuardBase
  id: CP14ClothingCloakGuardSyurko
  name: guard syurko
  description: A long and roomy cloak that serves to protect your armour.
  components:
  - type: Sprite
    sprite: _CP14/Clothing/Cloak/Roles/Guard/guard_syurko.rsi
  - type: Clothing
    sprite: _CP14/Clothing/Cloak/Roles/Guard/guard_syurko.rsi
