- type: job
  id: CP14Commandant
  name: cp14-job-name-commandant
  description: cp14-job-desc-commandant
  playTimeTracker: CP14JobCommandant
  startingGear: CP14CommandantGear
  icon: "CP14JobIconCommandant"
  requireAdminNotify: true
  joinNotifyCrew: true
  canBeAntag: false
  supervisors: cp14-job-supervisors-command
  weight: 2
  requirements:
    - !type:DepartmentTimeRequirement
      department: CP14Bank
      time: 7800 # 2 hours
  special:
  - !type:CP14AddKnowledgeSpecial
    knowledge:
    - WoodWork

- type: startingGear
  id: CP14CommandantGear
  equipment:
    belt2: CP14WalletFilledTest
    keys: CP14KeyRingCommandant