
# Artisans

- type: playTimeTracker
  id: CP14JobApprentice

- type: playTimeTracker
  id: CP14JobAlchemist

- type: playTimeTracker
  id: CP14JobBlacksmith

- type: playTimeTracker
  id: CP14JobInnkeeper

# Mercenary

- type: playTimeTracker
  id: CP14JobGuildmaster

- type: playTimeTracker
  id: CP14JobAdventurer

# Guard

- type: playTimeTracker
  id: CP14JobGuardCommander

- type: playTimeTracker
  id: CP14JobGuard

# Trade guild

- type: playTimeTracker
  id: CP14JobCommandant

- type: playTimeTracker
  id: CP14JobMerchant

# Gods
- type: playTimeTracker
  id: CP14GodNature

- type: playTimeTracker
  id: CP14GodLumera