- type: department
  id: CP14Mercenary
  description: department-CP14Free-desc
  color: "#429976"
  roles:
  - CP14Adventurer
  - CP14Alchemist

- type: department
  id: CP14Command
  description: department-CP14Command-desc
  color: "#fadb3e"
  roles:
  - CP14Captain
