- type: department
  id: CP14Gods
  name: department-CP14Gods
  description: department-CP14Gods-desc
  weight: 666 # >:)
  color: "#ffffff"
  roles:
  - CP14GodNature

- type: department
  id: CP14Command
  name: department-CP14Command
  description: department-CP14Command-desc
  primary: false
  weight: 10
  color: "#3ec8fa"
  editorHidden: true #temp
  roles:
  - CP14GuardCommander
  - CP14Guildmaster

- type: department
  id: CP14Guard
  name: department-CP14Guard
  description: department-CP14Guard-desc
  weight: 9
  color: "#576384"
  editorHidden: true #temp
  roles:
  - CP14GuardCommander
  - CP14Guard

- type: department
  id: CP14Artisan
  name: department-CP14Artisan
  description: department-CP14Artisan-desc
  weight: 7
  color: "#834833"
  roles:
  - CP14Merchant
  - CP14Alchemist
  - CP14Blacksmith
  - CP14Apprentice
  - CP14Innkeeper

- type: department
  id: CP14Mercenary
  name: department-CP14Mercenary
  description: department-CP14Mercenary-desc
  weight: 6
  color: "#588151"
  roles:
  - CP14Guildmaster
  - CP14Adventurer