- type: department
  id: CP14Command
  name: department-CP14Command
  description: department-CP14Command-desc
  primary: false
  weight: 10
  color: "#3ec8fa"
  roles:
  - CP14Commandant
  - CP14GuardCommander
  - CP14Guildmaster

- type: department
  id: CP14Guard
  name: department-CP14Guard
  description: department-CP14Guard-desc
  weight: 1
  color: "#576384"
  roles:
  - CP14GuardCommander
  - CP14Guard

- type: department
  id: CP14Bank
  name: department-CP14Bank
  description: department-CP14Bank-desc
  weight: 9
  color: "#fadb3e"
  roles:
  - CP14Commandant
  - CP14Banker

- type: department
  id: CP14Mercenary
  name: department-CP14Mercenary
  description: department-CP14Mercenary-desc
  weight: 0
  color: "#588151"
  roles:
  - CP14Guildmaster
  - CP14Apprentice
  - CP14Adventurer
  - CP14Alchemist
  - CP14Innkeeper
  - CP14Blacksmith