- type: entity
  parent: CP14ClothingShirtBase
  id: CP14ClothingShirtCottonBlack
  name: cotton black shirt
  components:
  - type: Sprite
    sprite: _CP14/Clothing/Shirt/Roles/General/black.rsi
  - type: Clothing
    sprite: _CP14/Clothing/Shirt/Roles/General/black.rsi

- type: entity
  parent: CP14ClothingShirtBase
  id: CP14ClothingShirtCottonBlue
  name: cotton blue shirt
  components:
  - type: Sprite
    sprite: _CP14/Clothing/Shirt/Roles/General/blue.rsi
  - type: Clothing
    sprite: _CP14/Clothing/Shirt/Roles/General/blue.rsi

- type: entity
  parent: CP14ClothingShirtBase
  id: CP14ClothingShirtCottonBlueCollar
  name: cotton blue collar shirt
  components:
  - type: Sprite
    sprite: _CP14/Clothing/Shirt/Roles/General/blue_collar.rsi
  - type: Clothing
    sprite: _CP14/Clothing/Shirt/Roles/General/blue_collar.rsi

- type: entity
  parent: CP14ClothingShirtBase
  id: CP14ClothingShirtMercenary
  name: mercenary shirt
  description: A mercenary's colourful shirt.
  components:
  - type: Sprite
    sprite: _CP14/Clothing/Shirt/Roles/General/mercenary.rsi
  - type: Clothing
    sprite: _CP14/Clothing/Shirt/Roles/General/mercenary.rsi

- type: entity
  parent: CP14ClothingShirtBase
  id: CP14ClothingShirtBlueOpen
  name: cotton blue open shirt
  components:
  - type: Sprite
    sprite: _CP14/Clothing/Shirt/Roles/General/open_blue.rsi
  - type: Clothing
    sprite: _CP14/Clothing/Shirt/Roles/General/open_blue.rsi

- type: entity
  parent: CP14ClothingShirtBase
  id: CP14ClothingShirtRedOpen
  name: cotton red open shirt
  components:
  - type: Sprite
    sprite: _CP14/Clothing/Shirt/Roles/General/open_red.rsi
  - type: Clothing
    sprite: _CP14/Clothing/Shirt/Roles/General/open_red.rsi

- type: entity
  parent: CP14ClothingShirtBase
  id: CP14ClothingShirtYellowOpen
  name: cotton yellow open shirt
  components:
  - type: Sprite
    sprite: _CP14/Clothing/Shirt/Roles/General/open_yellow.rsi
  - type: Clothing
    sprite: _CP14/Clothing/Shirt/Roles/General/open_yellow.rsi

- type: entity
  parent: CP14ClothingShirtBase
  id: CP14ClothingShirtCottonPurple
  name: cotton purple shirt
  components:
  - type: Sprite
    sprite: _CP14/Clothing/Shirt/Roles/General/purple.rsi
  - type: Clothing
    sprite: _CP14/Clothing/Shirt/Roles/General/purple.rsi

- type: entity
  parent: CP14ClothingShirtBase
  id: CP14ClothingShirtCottonRed
  name: cotton red shirt
  components:
  - type: Sprite
    sprite: _CP14/Clothing/Shirt/Roles/General/red.rsi
  - type: Clothing
    sprite: _CP14/Clothing/Shirt/Roles/General/red.rsi

- type: entity
  parent: CP14ClothingShirtBase
  id: CP14ClothingShirtCottonWhite
  name: cotton white shirt
  components:
  - type: Sprite
    sprite: _CP14/Clothing/Shirt/Roles/General/white.rsi
  - type: Clothing
    sprite: _CP14/Clothing/Shirt/Roles/General/white.rsi

- type: entity
  parent: CP14ClothingShirtBase
  id: CP14ClothingShirtCottonWhiteBelt
  name: cotton white belt shirt
  components:
  - type: Sprite
    sprite: _CP14/Clothing/Shirt/Roles/General/white_belt.rsi
  - type: Clothing
    sprite: _CP14/Clothing/Shirt/Roles/General/white_belt.rsi

- type: entity
  parent: CP14ClothingShirtBase
  id: CP14ClothingShirtCottonWhiteBrownVest
  name: cotton white brown vest shirt
  components:
  - type: Sprite
    sprite: _CP14/Clothing/Shirt/Roles/General/white_brown_vest.rsi
  - type: Clothing
    sprite: _CP14/Clothing/Shirt/Roles/General/white_brown_vest.rsi

- type: entity
  parent: CP14ClothingShirtCottonWhiteBrownVest
  id: CP14ClothingShirtCottonWhiteBrownVest2
  components:
  - type: Sprite
    sprite: _CP14/Clothing/Shirt/Roles/General/white_brown_vest2.rsi
  - type: Clothing
    sprite: _CP14/Clothing/Shirt/Roles/General/white_brown_vest2.rsi

- type: entity
  parent: CP14ClothingShirtCottonWhiteBrownVest
  id: CP14ClothingShirtCottonWhiteBrownVest3
  components:
  - type: Sprite
    sprite: _CP14/Clothing/Shirt/Roles/General/white_brown_vest3.rsi
  - type: Clothing
    sprite: _CP14/Clothing/Shirt/Roles/General/white_brown_vest3.rsi

- type: entity
  parent: CP14ClothingShirtBase
  id: CP14ClothingShirtCottonWhiteCollar
  name: cotton white collar shirt
  components:
  - type: Sprite
    sprite: _CP14/Clothing/Shirt/Roles/General/white_collar.rsi
  - type: Clothing
    sprite: _CP14/Clothing/Shirt/Roles/General/white_collar.rsi

- type: entity
  parent: CP14ClothingShirtBase
  id: CP14ClothingShirtCottonWhiteGreenVest
  name: cotton white green vest shirt
  components:
  - type: Sprite
    sprite: _CP14/Clothing/Shirt/Roles/General/white_green_vest.rsi
  - type: Clothing
    sprite: _CP14/Clothing/Shirt/Roles/General/white_green_vest.rsi

- type: entity
  parent: CP14ClothingShirtCottonWhiteGreenVest
  id: CP14ClothingShirtCottonWhiteGreenVest2
  components:
  - type: Sprite
    sprite: _CP14/Clothing/Shirt/Roles/General/white_green_vest2.rsi
  - type: Clothing
    sprite: _CP14/Clothing/Shirt/Roles/General/white_green_vest2.rsi

- type: entity
  parent: CP14ClothingShirtBase
  id: CP14ClothingShirtCottonYellow
  name: cotton yellow shirt
  components:
  - type: Sprite
    sprite: _CP14/Clothing/Shirt/Roles/General/yellow.rsi
  - type: Clothing
    sprite: _CP14/Clothing/Shirt/Roles/General/yellow.rsi

- type: entity
  parent: CP14ClothingShirtBase
  id: CP14ClothingShirtCottonYellowCollar
  name: cotton yellow collar shirt
  components:
  - type: Sprite
    sprite: _CP14/Clothing/Shirt/Roles/General/yellow_collar.rsi
  - type: Clothing
    sprite: _CP14/Clothing/Shirt/Roles/General/yellow_collar.rsi

- type: entity
  parent: CP14ClothingShirtBase
  id: CP14ClothingShirtYellowWizard
  name: yellow wizard shirt
  description: A loose magician's shirt, comfortable and nice looking.
  components:
  - type: Sprite
    sprite: _CP14/Clothing/Shirt/Roles/General/yellow_wizard.rsi
  - type: Clothing
    sprite: _CP14/Clothing/Shirt/Roles/General/yellow_wizard.rsi
