- type: job
  id: CP14Adventurer
  name: cp14-job-name-adventurer
  description: cp14-job-desc-adventurer
  playTimeTracker: CP14JobAdventurer
  startingGear: CP14AdventurerGear
  icon: "CP14JobIconAdventurer"
  supervisors: cp14-job-supervisors-guildmaster

- type: startingGear
  id: CP14AdventurerGear
  storage:
    back:
    - CP14EnergyCrystalMedium
    - CP14EnergyCrystalMedium
  equipment:
    keys: CP14BaseKeyRing
    belt1: CP14WalletFilledTest

