- type: job
  id: CP14Blacksmith
  name: cp14-job-name-blacksmith
  description: cp14-job-desc-blacksmith
  playTimeTracker: CP14JobBlacksmith
  startingGear: CP14BlacksmithGear
  icon: "CP14JobIconBlacksmith"
  supervisors: cp14-job-supervisors-command
  special:
  - !type:CP14AddKnowledgeSpecial
    knowledge:
    - WoodWork
    - MetallMelting
    - MetallForging
    - Glasswork

- type: startingGear
  id: CP14BlacksmithGear
  storage:
    back:
    - CP14EnergyCrystalSmall
    - CP14EnergyCrystalSmall
  equipment:
    belt1: CP14WalletFilledTest
    keys: CP14KeyRingBlacksmith