- type: job
  id: CP14Guildmaster
  setPreference: true
  name: cp14-job-name-guildmaster
  description: cp14-job-desc-guildmaster
  playTimeTracker: CP14JobGuildmaster
  startingGear: CP14GuildmasterGear
  icon: "CP14JobIconGuildmaster"
  requireAdminNotify: true
  joinNotifyCrew: true
  canBeAntag: false
  supervisors: cp14-job-supervisors-command
  weight: 3
  requirements:
    - !type:RoleTimeRequirement
      role: CP14GuildWorker
      time: 7200 # 2 hours
    - !type:RoleTimeRequirement
      role: CP14JobAdventurer
      time: 18000 # 5 hours
  special:
    - !type:AddComponentSpecial
      components:
      - type: CP14SalaryCounter
        salary: 100

- type: startingGear
  id: CP14GuildmasterGear
  storage:
    back:
    - CP14EnergyCrystalMedium
  equipment:
    belt: CP14WalletFilledTest
    keys: CP14KeyRingGuildmaster