- type: job
  id: CP14GuardCommander
  name: cp14-job-name-guard-commander
  description: cp14-job-desc-guard-commander
  playTimeTracker: CP14JobGuardCommander
  startingGear: CP14GuardCommanderGear
  icon: "CP14JobIconGuardCommander"
  requireAdminNotify: true
  joinNotifyCrew: true
  canBeAntag: false
  supervisors: cp14-job-supervisors-command
  weight: 2
  setPreference: true
  requirements:
    - !type:DepartmentTimeRequirement
      department: CP14Guard
      time: 3600 # 1 hours
  special:
    - !type:CP14LearnSkillsSpecial
      skills:
      - SwordMastery

- type: startingGear
  id: CP14GuardCommanderGear
  equipment:
    keys: CP14KeyRingGuardCommander
    belt1: CP14WalletFilledTest