- type: job
  id: CP14Guard
  name: cp14-job-name-guard
  description: cp14-job-desc-guard
  playTimeTracker: CP14JobGuard
  startingGear: CP14GuardGear
  icon: "CP14JobIconGuard"
  supervisors: cp14-job-supervisors-guard-commander
  special:
    - !type:CP14LearnSkillsSpecial
      skills:
      - SwordMastery

- type: startingGear
  id: CP14GuardGear
  equipment:
    keys: CP14KeyRingGuard
    belt: CP14WalletFilledTest