- type: startingGear
  id: CP14DeathMatchGear
  equipment:
    cloak: CP14ClothingCloakFurcapeBlue
    shirt: CP14ClothingShirtCottonBlack
    pants: CP14ClothingPantsLoincloth
    shoes: CP14ClothingShoesSandals
  inhand:
    - CP14ModularIronDagger
    - CP14ModularIronDagger

