- type: entity
  parent: CP14ClothingOuterClothingBase
  id: CP14ClothingOuterClothingBankerWaistCoat
  name: "banker's waistcoat"
  description: Stylish waistcoat made of expensive leather. A special uniform for bank employees that makes customers feel like beggars.
  components:
  - type: Sprite
    sprite: _CP14/Clothing/OuterClothing/Roles/Bank/vest_banker.rsi
  - type: Clothing
    sprite: _CP14/Clothing/OuterClothing/Roles/Bank/vest_banker.rsi

- type: entity
  parent: CP14ClothingOuterClothingBankerWaistCoat
  id: CP14ClothingOuterClothingBankerWaistCoatOpen
  name: "open banker's waistcoat"
  components:
  - type: Sprite
    sprite: _CP14/Clothing/OuterClothing/Roles/Bank/vest_banker_open.rsi
  - type: Clothing
    sprite: _CP14/Clothing/OuterClothing/Roles/Bank/vest_banker_open.rsi