- type: cp14DemiplaneLocation
  id: T1Caves
  locationConfig: CP14ExpeditionCaves
  tags:
  - CP14DemiplanOre
  components:
  - type: CP14WeatherController
    entries:
    - visuals: CP14Mist

- type: dungeonConfig
  id: CP14ExpeditionCaves
  layers:
    # Masks (from center to border!)
    - !type:PrototypeDunGen
      proto: CP14ExpeditionCavesFloorMaskBorder
    - !type:PrototypeDunGen
      proto: CP14ExpeditionCavesFloorMaskStone
    - !type:PrototypeDunGen
      proto: CP14ExpeditionCavesFloorMaskAir
    # Exterior rooms
    #here
    # Biome Spawner fills (from border to center!) order is very important! For inexplicable reasons, only a certain sequence works!
    - !type:PrototypeDunGen
      proto: CP14ExpeditionCavesFillBorder
    - !type:PrototypeDunGen
      proto: CP14ExpeditionCavesFillAir
    - !type:PrototypeDunGen
      proto: CP14ExpeditionCavesFillCave
    # Mobs
    - !type:MobsDunGen
      minCount: 5
      maxCount: 10
      groups:
      - id: CP14SpawnMobUndeadZombie
        amount: 1
    # Enter and Exit
    - !type:MobsDunGen
      minCount: 1
      maxCount: 2
      groups:
      - id: CP14DemiplaneEntryPointMarker
        amount: 1
    - !type:MobsDunGen
      minCount: 2
      maxCount: 2
      groups:
      - id: CP14DemiplanePassway
        amount: 1
    # Loot
    - !type:EntityTableDunGen
      minCount: 10
      maxCount: 25
      table: !type:NestedSelector
        tableId: CP14TableExpeditionLootCommon

- type: dungeonConfig
  id: CP14ExpeditionCavesFloorMaskAir
  layers:
  - !type:NoiseDistanceDunGen
    size: 80, 80
    distanceConfig: !type:DunGenEuclideanSquaredDistance
      blendWeight: 0.5
    layers:
    - tile: CP14FloorGrass
      threshold: 0.50
      noise:
        frequency: 0.030
        noiseType: OpenSimplex2
        fractalType: FBm
        octaves: 5
        lacunarity: 2
        gain: 0.5

- type: dungeonConfig
  id: CP14ExpeditionCavesFloorMaskStone
  layers:
  - !type:NoiseDistanceDunGen
    size: 120, 120
    distanceConfig: !type:DunGenEuclideanSquaredDistance
      blendWeight: 0.9
    layers:
    - tile: CP14FloorSand
      threshold: 0.50
      noise:
        frequency: 0.010
        noiseType: OpenSimplex2
        fractalType: FBm
        octaves: 5
        lacunarity: 2
        gain: 0.5

- type: dungeonConfig
  id: CP14ExpeditionCavesFloorMaskBorder
  layers:
  - !type:NoiseDistanceDunGen
    size: 130, 130
    distanceConfig: !type:DunGenEuclideanSquaredDistance
      blendWeight: 1
    layers:
    - tile: CP14FloorBase
      threshold: 0.50
      noise:
        frequency: 0.010
        noiseType: OpenSimplex2
        fractalType: FBm
        octaves: 5
        lacunarity: 2
        gain: 0.5

- type: dungeonConfig
  id: CP14ExpeditionCavesFillAir
  reserveTiles: true
  data:
    entities:
      Fill: CP14BiomeSpawnerCaveEmpty
  layers:
  - !type:FillGridDunGen
    allowedTiles:
    - CP14FloorGrass

- type: dungeonConfig
  id: CP14ExpeditionCavesFillCave
  reserveTiles: true
  data:
    entities:
      Fill: CP14BiomeSpawnerCave
  layers:
  - !type:FillGridDunGen
    allowedTiles:
    - CP14FloorSand

- type: dungeonConfig
  id: CP14ExpeditionCavesFillBorder
  reserveTiles: true
  data:
    entities:
      Fill: CP14WallStoneIndestructable
  layers:
  - !type:FillGridDunGen
    allowedTiles:
    - CP14FloorBase