- type: job
  id: CP14Alchemist
  name: cp14-job-name-alchemist
  description: cp14-job-desc-alchemist
  playTimeTracker: CP14JobAlchemist
  startingGear: CP14AlchemistGear
  icon: "CP14JobIconAlchemist"
  supervisors: cp14-job-supervisors-command
  special:
    - !type:CP14LearnSkillsSpecial
      skills:
      - AlchemyVision
  requirements:
    #- !type:RoleTimeRequirement
    #  role: CP14JobApprentice
    #  time: 3600 # 1 hours
    - !type:TraitsRequirement
      inverted: true
      traits:
      - CP14ManaWasting

- type: startingGear
  id: CP14AlchemistGear
  storage:
    back:
    - CP14EnergyCrystalMedium
    - CP14EnergyCrystalMedium
  equipment:
    belt1: CP14WalletFilledTest
    keys: CP14KeyRingAlchemist
    neck: CP14MagicHealingStaff