- type: job
  id: CP14Apprentice
  name: cp14-job-name-apprentice
  description: cp14-job-desc-apprentice
  playTimeTracker: CP14JobApprentice
  startingGear: CP14ApprenticeGear
  icon: "CP14JobIconApprentice"
  supervisors: cp14-job-supervisors-command
  special:
  - !type:CP14AddKnowledgeSpecial
    knowledge:
    - WoodWork

- type: startingGear
  id: CP14ApprenticeGear
  storage:
    back:
    - CP14EnergyCrystalSmall
    - CP14EnergyCrystalSmall
  equipment:
    keys: CP14BaseKeyRing
    belt2: CP14WalletFilledTest