- type: job
  id: CP14Blacksmith
  name: cp14-job-name-blacksmith
  description: cp14-job-desc-blacksmith
  playTimeTracker: CP14JobBlacksmith
  startingGear: CP14BlacksmithGear
  icon: "CP14JobIconBlacksmith"
  supervisors: cp14-job-supervisors-command
  special:
    - !type:CP14AddTradingReputationSpecial
      factions:
      - DwarfMining
      - Thaumaturgy
      - HomeDecor
      - Butchers # For leather
      - Tailors
    - !type:CP14LearnSkillsSpecial
      skills:
      - CopperMelting
      - IronMelting
      - GoldMelting
      - GlassMelting
      - MithrilMelting
      - TraderWit
  requirements:
    - !type:DepartmentTimeRequirement
      department: CP14Artisan
      time: 3600 # 1 hours

- type: startingGear
  id: CP14BlacksmithGear
  storage:
    back:
    - CP14EnergyCrystalMedium
    - CP14EnergyCrystalMedium
  equipment:
    belt: CP14WalletFilledTest
    keys: CP14KeyRingBlacksmith
